import type { Metadata } from "next";
import Link from "next/link";
import { RiCustomerService2Line, RiFileList3Line, RiMailLine, RiShieldKeyholeLine } from "react-icons/ri";

export const metadata: Metadata = {
	title: "Política de Privacidade",
	description:
		"Esta página foca na nossa política de privacidade descrevendo o que todos os sistemas próprios e de parceiros fornecem quanto a dados pessoais.",
	twitter: {
		title: "Política de Privacidade",
		description:
			"Esta página foca na nossa política de privacidade descrevendo o que todos os sistemas próprios e de parceiros fornecem quanto a dados pessoais.",
	},
};

export default function PrivacyPage() {
	return (
		<div className="flex flex-col gap-8 mt-8 max-w-4xl mx-auto px-6 lg:px-0">
			{/* Cabeçalho */}
			<div className="text-center mb-4">
				<h1 className="text-4xl md:text-5xl font-bold text-white mb-6 flex items-center justify-center gap-4">
					<div className="w-2 h-12 bg-gradient-to-b from-red-600 to-red-500 rounded-full" />
					Privacy Policy
					<div className="w-2 h-12 bg-gradient-to-b from-red-600 to-red-500 rounded-full" />
				</h1>
				<div className="w-24 h-1 bg-gradient-to-r from-red-600 to-red-500 rounded-full mx-auto mb-4"></div>
				<p className="text-gray-400 text-lg">Last updated: March 09, 2024</p>
			</div>

			{/* Introdução */}
			<div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-8 shadow-2xl border border-gray-700">
				<p className="text-lg leading-relaxed text-gray-300 mb-4">
					This Privacy Policy describes Our policies and procedures on the
					collection, use and disclosure of Your information when You use the
					Service and tells You about Your privacy rights and how the law
					protects You.
				</p>
				<p className="text-lg leading-relaxed text-gray-300">
					We use Your Personal data to provide and improve the Service. By using
					the Service, You agree to the collection and use of information in
					accordance with this Privacy Policy.
				</p>
			</div>

			{/* Interpretation and Definitions */}
			<div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-8 shadow-2xl border border-gray-700">
				<h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
					<RiFileList3Line className="text-red-500" />
					Interpretation and Definitions
				</h2>

				<div className="space-y-6">
					<div>
						<h3 className="text-xl font-semibold text-white mb-3">
							Interpretation
						</h3>
						<p className="text-lg leading-relaxed text-gray-300">
							The words of which the initial letter is capitalized have meanings
							defined under the following conditions. The following definitions
							shall have the same meaning regardless of whether they appear in
							singular or in plural.
						</p>
					</div>

					<div>
						<h3 className="text-xl font-semibold text-white mb-3">
							Definitions
						</h3>
						<p className="text-lg leading-relaxed text-gray-300 mb-4">
							For the purposes of this Privacy Policy:
						</p>
						<div className="grid gap-3">
							{[
								{
									term: "Account",
									definition:
										"means a unique account created for You to access our Service or parts of our Service.",
								},
								{
									term: "Company",
									definition:
										"(referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Império Network.",
								},
								{
									term: "Cookies",
									definition:
										"are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
								},
								{ term: "Country", definition: "refers to: Portugal" },
								{
									term: "Device",
									definition:
										"means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
								},
								{
									term: "Personal Data",
									definition:
										"is any information that relates to an identified or identifiable individual.",
								},
								{ term: "Service", definition: "refers to the Website." },
								{
									term: "Service Provider",
									definition:
										"means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
								},
								{
									term: "Usage Data",
									definition:
										"refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
								},
								{
									term: "Website",
									definition: `refers to Império Network, accessible from ${process.env.SITE_URL}`,
								},
								{
									term: "You",
									definition:
										"means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
								},
							].map((item) => (
								<div
									key={item.term}
									className="flex gap-3 p-3 bg-gray-800/50 rounded-lg"
								>
									<div className="w-2 h-2 bg-red-500 rounded-full mt-2 flex-shrink-0" />
									<div>
										<strong className="text-white">{item.term}</strong>{" "}
										<span className="text-gray-300 ml-1">
											{item.definition}
										</span>
									</div>
								</div>
							))}
						</div>
					</div>
				</div>
			</div>

			{/* Collecting and Using Your Personal Data */}
			<div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-8 shadow-2xl border border-gray-700">
				<h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
					<RiShieldKeyholeLine className="text-red-500" />
					Collecting and Using Your Personal Data
				</h2>

				<div className="space-y-8">
					{/* Types of Data Collected */}
					<div>
						<h3 className="text-xl font-semibold text-white mb-4">
							Types of Data Collected
						</h3>

						{/* Personal Data */}
						<div className="mb-6">
							<h4 className="text-lg font-semibold text-white mb-3">
								Personal Data
							</h4>
							<p className="text-lg leading-relaxed text-gray-300 mb-3">
								While using Our Service, We may ask You to provide Us with
								certain personally identifiable information that can be used to
								contact or identify You. Personally identifiable information may
								include, but is not limited to:
							</p>
							<ul className="list-disc list-inside text-gray-300 space-y-1 ml-4">
								<li>Email address</li>
								<li>First name and last name</li>
								<li>Usage Data</li>
							</ul>
						</div>

						{/* Usage Data */}
						<div className="mb-6">
							<h4 className="text-lg font-semibold text-white mb-3">
								Usage Data
							</h4>
							<p className="text-lg leading-relaxed text-gray-300 mb-3">
								Usage Data is collected automatically when using the Service.
							</p>
							<p className="text-lg leading-relaxed text-gray-300 mb-3">
								Usage Data may include information such as Your Device's
								Internet Protocol address (e.g. IP address), browser type,
								browser version, the pages of our Service that You visit, the
								time and date of Your visit, the time spent on those pages,
								unique device identifiers and other diagnostic data.
							</p>
						</div>

						{/* Tracking Technologies */}
						<div>
							<h4 className="text-lg font-semibold text-white mb-3">
								Tracking Technologies and Cookies
							</h4>
							<p className="text-lg leading-relaxed text-gray-300 mb-3">
								We use Cookies and similar tracking technologies to track the
								activity on Our Service and store certain information.
							</p>

							<div className="grid gap-4 mb-4">
								{[
									{
										title: "Cookies or Browser Cookies",
										description:
											"A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.",
									},
									{
										title: "Web Beacons",
										description:
											"Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages.",
									},
								].map((item) => (
									<div
										key={item.title}
										className="p-4 bg-gray-800/50 rounded-lg"
									>
										<strong className="text-white">{item.title}</strong>
										<p className="text-gray-300 mt-1">{item.description}</p>
									</div>
								))}
							</div>
						</div>
					</div>

					{/* Use of Your Personal Data */}
					<div>
						<h3 className="text-xl font-semibold text-white mb-4">
							Use of Your Personal Data
						</h3>
						<p className="text-lg leading-relaxed text-gray-300 mb-4">
							The Company may use Personal Data for the following purposes:
						</p>

						<div className="grid gap-3">
							{[
								"To provide and maintain our Service, including to monitor the usage of our Service.",
								"To manage Your Account: to manage Your registration as a user of the Service.",
								"For the performance of a contract: the development, compliance and undertaking of the purchase contract.",
								"To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.",
								"To provide You with news, special offers and general information about other goods, services and events.",
								"To manage Your requests: To attend and manage Your requests to Us.",
								"For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring.",
								"For other purposes: We may use Your information for other purposes, such as data analysis.",
							].map((purpose, index) => (
								<div
									key={index + purpose}
									className="flex gap-3 p-3 bg-gray-800/50 rounded-lg"
								>
									<div className="w-2 h-2 bg-blue-500 rounded-full mt-2 flex-shrink-0" />
									<span className="text-gray-300">{purpose}</span>
								</div>
							))}
						</div>
					</div>
				</div>
			</div>

			{/* Contact Section */}
			<div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-8 shadow-2xl border border-gray-700">
				<h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
					<RiCustomerService2Line className="text-red-500" />
					Contact Us
				</h2>
				<p className="text-lg leading-relaxed text-gray-300 mb-4">
					If you have any questions about this Privacy Policy, You can contact
					us:
				</p>
				<Link
					href="mailto:imperiogames2019@gmail.com"
					target="_blank"
					className="inline-flex items-center gap-2 bg-red-600 hover:bg-red-500 text-white px-6 py-3 rounded-xl font-medium transition-all duration-300"
				>
					<RiMailLine />
					imperiogames2019@gmail.com
				</Link>
			</div>

			{/* Final Note */}
			<div className="text-center mt-2 p-8 bg-gradient-to-r from-blue-600/10 to-purple-600/10 rounded-2xl border border-blue-500/20">
				<h2 className="text-2xl font-bold text-white mb-4">
					🔒 Your Privacy Matters
				</h2>
				<p className="text-gray-300 text-lg">
					We are committed to protecting your personal information and being
					transparent about our practices.
				</p>
			</div>
		</div>
	);
}
